* Engines
This is a free and open-source (FOSS) curation
of LM models and their capabilities.

| License | Discord server invite         |
|---------+-------------------------------|
| =GPL-3= | https://discord.gg/JwKGbAdNHR |

See the =prompts= repo for detailed documentation.

http://github.com/semiosis/prompts

Specifying an engine in a =.prompt= means that
you don't have to specify the parameters
contained by that engine

Typically, the engine specifies the =model=
and the =lm-command=.

An engine may also load another engine as a
template. This is done by supplying the
=include= key with the title of another
=engine=.

* Terminology
+ foundation :: This means that a model is generalised and capable of many tasks via prompting.

[[./glossary.txt]]

+ downstream-engines: Usually means finetuned (extra training).

** layers vs specialties vs requirements

* Philosophy
- When defining attributes of engines it's
  important to not value preciseness over
  pragmatism. For example, I have specified
  "foundation, nl, code" for codex as if it had
  an independent training step for NL on top of the
  foundation model, which it did not.

* Resources
+ Foundation models :: https://arxiv.org/abs/2108.07258